### ISSUE TITLE
Limit rate issue

### ISSUE THREAD

**Issue by HereComesTheRainAgain** [laurentS/slowapi#2]
I've tested limit rate locally and it works fine.

After I deployed application on AWS, rates did't work at all until I set redis as storage.

But even with redis, rate limit seems to be broken.
Limit is exceeded after ~10th attempt, and I've set limit to 5.

I've checked redis value for the key inserted by limiter, and I think it did not count every attempt.

I'm using FastAPI 0.45.0 and slowapi 0.1.1

**Comment by laurentS** [comment]
Hi @HereComesTheRainAgain thanks for reporting the issue! I've only tested against FastAPI 0.52.0, so it might be worth checking with that version to see if the issue is still present.

That said, could you share the exact configuration you used so I can try and replicate your setup? The route decorator and limits you've set, and how you instantiated the `Limiter` class?

**Comment by HereComesTheRainAgain** [comment]
Sure,

there is limiter class:
`limiter = Limiter(key_func=get_remote_address, storage_uri=config.REDIS_URL)`

I've used this decorator:
`@limiter.limit("5/minute")`

And this is app setup:
```
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
```

**Comment by laurentS** [comment]
By default, the limiter uses a `fixed-window` strategy, which is described [here](https://limits.readthedocs.io/en/stable/strategies.html). With this setup, it is possible to go over the 5/minute limit, as is explained in the link. You could try passing `strategy="moving-window"` or `strategy="fixed-window-elastic-expiry"` to the `Limiter` constructor and see if that is the issue. If not, I'll keep digging :)

**Comment by HereComesTheRainAgain** [comment]
I will try with `strategy="moving-window"`, it seems like best choice to me.
Will write to you after I test it.

Thanks a lot!

**Comment by HereComesTheRainAgain** [comment]
Hi @laurentS,

I have changed strategy to `"moving-window"` but issue is still present.

I can confirm that issue occurs because counter in the redis does not have correct value and is not increased on every request.

**Comment by laurentS** [comment]
@HereComesTheRainAgain I have been trying a few variants locally but have not been able to reproduce your issue. Another idea to try and narrow down the cause: I imagine your AWS deployment is using more than one FastAPI worker. Would you be able to test with a single worker to see if the problem is still present?

**Comment by HereComesTheRainAgain** [comment]
@laurentS you are right, we use more than 1 worker.
Could you, please, try to use 1 worker per core locally, thats what we have on AWS?

**Comment by laurentS** [comment]
@HereComesTheRainAgain I have tried running locally with 4 gunicorn workers, but have not been able to reproduce the problem you're facing.
How many requests did you hit the server with before it failed? I have not load tested, so I'm not sure how far the limits can stretch.

Here are a few more ideas:
- redis has 16 databases (0 to 15). Are all your requests hitting the same db?
- you seem to be using `get_remote_address` to identify users. Depending on your setup, the way it determines the user's IP may not work
- I monitored the stream of commands going to redis with `redis-cli monitor` and each request logs something like this:
```
1587915964.138836 [0 172.31.0.9:43226] "EVALSHA" "0d23cf1ccf81ad1452ccf307e1938d99997a6073" "1" "LIMITER/172.31.0.3//myendpoint//200/1/minute" "60"
1587915964.138871 [0 lua] "incr" "LIMITER/172.31.0.3//myendpoint//200/1/minute"
```
This is for an endpoint limited to 200/minute, where the backend is placed behind a traefik proxy, both running in docker containers (using https://github.com/tiangolo/full-stack-fastapi-postgresql).
- Have you managed to test the same setup but with a single gunicorn worker instead of multiples ones? It would help in figuring out if it's a concurrency issue or something else.

**Comment by HereComesTheRainAgain** [comment]
@laurentS I've checked `redis-cli` on our AWS instance, and it seems to me that `get_remote_address` works fine, since I only had one `LIMITER ...` key.
So it probably have something to do with our setup, since all is working OK on your side. 

I will look into this and write if I come to any conclusion.

Thanks for the effort!

**Comment by HereComesTheRainAgain** [comment]
@laurentS issue is caused because our app is not getting right IP, it has to do something with `uvicorn` configuration.

We need to set `forwarded_allow_ips` parameter to `*` in order to get right client info. 

When `uvicorn` releases version which contains changes from PR related to that part, I will test everything again and if it works - close this issue.

**Comment by HereComesTheRainAgain** [comment]
@laurentS the issue was not related to your library, but to the `uvicorn`.
It will probably be fixed after this PR is released: https://github.com/encode/uvicorn/pull/591

**Comment by laurentS** [comment]
@HereComesTheRainAgain thanks for the update, glad that you managed to figure out your issue!
