### ISSUE TITLE
Rate limit is not shared if the endpoint has path parameters

### ISSUE THREAD

**Issue by riwu** [laurentS/slowapi#217]
FastAPI:
```
@app.get("/users/{user_id}")
@limiter.limit("1/minute")
def get_user(user_id: int):
    pass
```

The queries `/users/1` and `/users/2` would not share a limit unless I use `shared_limit`.  
Is this an expected behavior?

**Comment by thentgesMindee** [comment]
This looks like the expected behavior indeed.
However, there is the `key_style` argument that can be used to change this behavior when creating your Limiter instance, cf docs here: https://github.com/laurentS/slowapi/blob/master/docs/examples.md#use-view-functions-name-instead-of-full-endpoint-as-part-of-the-storage-key

TLDR: you can pass `key_style="endpoint"` if you want /users/1 and /users/2 to share the same limit (as well as any other users/x)
