### ISSUE TITLE
Question about get_ipaddr function

### ISSUE THREAD

**Issue by Nebulizer1213** [laurentS/slowapi#59]
this is how get_ipaddr currently works
`if "X_FORWARDED_FOR" in request.headers:
        r = request.headers["X_FORWARDED_FOR"]
        return r
    else:
        return request.client.host or "127.0.0.1"`
but the X-Forwarded-For gives two ips. So shouldn't it be
`if "X_FORWARDED_FOR" in request.headers:
        r = request.headers["X_FORWARDED_FOR"].split(",")[0]
        return r
    else:
        return request.client.host or "127.0.0.1"`

**Comment by Nebulizer1213** [comment]
actually I don't think it matters because it will still be unique to that user. Unless the second ip changes. I'm not really sure what the second ip is.

**Comment by Nebulizer1213** [comment]
just looked it up it is the proxy ip. I think it would still be best to do it like this `request.headers["X_FORWARDED_FOR"].split(",")[0]`

**Comment by laurentS** [comment]
@Nebulizer1213 I'm wondering if this might be due to how your server is configured, I don't recall seeing this duplicate IP.
Two comments though:
- as you point out, the limiter only really cares about having some sort of string to identify a user, it does not have to be an IP (this depends on your use case)
- the function in the code is just a convenience function to get you started, you don't have to use it at all. Instead you can implement whatever function you want that returns a string identifying your users, and pass it to the limiter constructor.

**Comment by Nebulizer1213** [comment]
ok thanks
